import React, { createContext, useContext, useState, useEffect } from 'react';

// Language interface
interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

// Available languages
export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳' }
];

// Translation object
const translations = {
  en: {
    // Login Page
    'app.title': 'AgroAnalytics',
    'app.subtitle': 'Smart Agriculture Analytics Platform',
    'login.welcome': 'Welcome Back',
    'login.description': 'Enter your email to receive a one-time password',
    'signup.title': 'Create Account',
    'signup.description': 'Join thousands of farmers using smart analytics',
    'signup.verify': 'Verify your email to complete account creation',
    'email.label': 'Email Address',
    'email.placeholder': 'farmer@example.com',
    'name.label': 'Full Name',
    'name.placeholder': 'John Farmer',
    'farmSize.label': 'Farm Size (acres)',
    'farmSize.placeholder': '100',
    'otp.label': 'One-Time Password',
    'otp.placeholder': 'Enter OTP',
    'otp.expires': 'OTP expires in:',
    'otp.resend': 'Resend OTP',
    'send.otp': 'Send OTP to my email',
    'sending.otp': 'Sending OTP...',
    'verifying': 'Verifying...',
    'get.started': 'Get Started',
    'send.verification': 'Send Verification Code',
    'complete.registration': 'Complete Registration',
    'login.tab': 'Login',
    'signup.tab': 'Sign Up',
    'no.account': 'No account found with this email. Please sign up first.',
    'switch.tab': "Don't have an account? Switch to the \"Sign Up\" tab to create one.",
    'data.driven': 'Data-Driven Agriculture',
    'data.description': 'Make informed decisions with real-time analytics, weather predictions, and AI-powered crop insights.',
    
    // Navbar
    'navbar.platform': 'Smart Agriculture Platform',
    'navbar.notifications': 'Notifications',
    'navbar.signout': 'Sign out',
    'navbar.profile': 'Profile Settings',
    'navbar.farm': 'Farm Management',
    'navbar.subscription': 'Subscription',
    'navbar.logout': 'Logout',
    'navbar.mark.all.read': 'Mark all read',
    'navbar.no.notifications': 'No notifications',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.weather': 'Weather',
    'sidebar.soil': 'Soil Health',
    'sidebar.crop': 'Crop Analytics',
    'sidebar.market': 'Market Trends',
    'sidebar.financial': 'Financial Planning',
    'sidebar.community': 'Community',
    'sidebar.government': 'Government Schemes',
    'sidebar.reports': 'Reports',
    
    // Dashboard
    'dashboard.title': 'Farm Dashboard',
    'dashboard.overview': 'Farm Overview',
    'dashboard.weather': 'Current Weather',
    'dashboard.temperature': 'Temperature',
    'dashboard.humidity': 'Humidity',
    'dashboard.wind': 'Wind Speed',
    'dashboard.pressure': 'Pressure',
    'dashboard.visibility': 'Visibility',
    'dashboard.crop.analytics': 'Crop Analytics',
    'dashboard.soil.health': 'Soil Health',
    'dashboard.market.trends': 'Market Trends',
    'dashboard.recent.activity': 'Recent Activity',
    'dashboard.irrigation': 'Irrigation Status',
    'dashboard.fertilizer': 'Fertilizer Schedule',
    'dashboard.pest.control': 'Pest Control',
    'dashboard.harvest': 'Harvest Planning',
    
    // Weather
    'weather.search.location': 'Search location...',
    
    // Language Selector
    'language.select': 'Select Language',
    'language.current': 'Current Language',
    
    // Voice Interface
    'voice.title': 'Voice Assistant',
    'voice.listening': 'Listening...',
    'voice.speaking': 'Speaking...',
    'voice.heard': 'You said',
    'voice.last.command': 'Last command',
    'voice.try.saying': 'Try saying:',
    'voice.language.info': 'Voice language',
    'voice.not.supported': 'Voice features not supported in this browser',
    'voice.commands.weather': 'What is the weather today?',
    'voice.commands.price': 'What are the crop prices?',
    'voice.commands.crop': 'Give me crop advice',
    'voice.commands.soil': 'Check soil health',
    'voice.commands.help': 'Help me',
    'voice.weather.response': 'Today\'s weather is sunny with 28°C temperature. Good for farming activities.',
    'voice.price.response': 'Current wheat price is ₹2,950 per quintal, rice ₹3,750 per quintal. Prices are trending upward.',
    'voice.crop.response': 'For this season, I recommend planting wheat or rice. Ensure proper irrigation and use organic fertilizers.',
    'voice.soil.response': 'Your soil pH is 6.8, which is good. Add compost to improve organic matter content.',
    'voice.help.response': 'I can help you with weather updates, crop prices, farming advice, and soil information. Just ask me!',
    'voice.unknown.response': 'I didn\'t understand that. Try asking about weather, prices, crops, or soil health.',
    
    // Market Price Intelligence
    'market.intelligence.title': 'Market Price Intelligence',
    'market.intelligence.subtitle': 'Real-time commodity prices and market trends',
    'market.last.updated': 'Last updated',
    'market.wheat': 'Wheat',
    'market.rice': 'Rice',
    'market.corn': 'Corn',
    'market.soybean': 'Soybean',
    'market.cotton': 'Cotton',
    'market.set.alert': 'Set Alert',
    'market.buy.now': 'Buy Now',
    'market.price.trends': 'Price Trends',
    'market.trends.description': 'Historical price movements for major commodities',
    'market.price.alerts': 'Price Alerts',
    'market.alert.when': 'Alert when price is',
    'market.alert.active': 'Active',
    'market.alert.inactive': 'Inactive',
    'market.alert.disable': 'Disable',
    'market.alert.enable': 'Enable',
    'market.insights.title': 'Market Insights',
    'market.insights.best.selling': 'Best Selling Time',
    'market.insights.best.selling.desc': 'Sell wheat in March-April for best prices',
    'market.insights.price.trend': 'Price Trend',
    'market.insights.price.trend.desc': 'Wheat prices expected to rise 5-8% next month',
    'market.insights.weather.impact': 'Weather Impact',
    'market.insights.weather.impact.desc': 'Rain forecast may affect crop quality and prices',
    'market.insights.government.schemes': 'Government Schemes',
    'market.insights.government.schemes.desc': 'MSP rates increased for wheat and rice this season',
    
    // Crop Advisory System
    'advisory.title': 'Crop Advisory System',
    'advisory.subtitle': 'Personalized farming guidance and recommendations',
    'advisory.growth.stage': 'Growth Stage',
    'advisory.expected.yield': 'Expected Yield',
    'advisory.market.price': 'Market Price',
    'advisory.profit.estimate': 'Profit Estimate',
    'advisory.tasks': 'Tasks',
    'advisory.alerts': 'Alerts',
    'advisory.schedule': 'Schedule',
    'advisory.recommendations': 'Recommendations',
    'advisory.weather.alerts': 'Weather Alerts',
    'advisory.pest.alerts': 'Pest Alerts',
    'advisory.disease.alerts': 'Disease Alerts',
    'advisory.irrigation.schedule': 'Irrigation Schedule',
    'advisory.fertilizer.schedule': 'Fertilizer Schedule',
    'advisory.current.recommendations': 'Current Recommendations',
    'advisory.upcoming.tasks': 'Upcoming Tasks',
    'crop.wheat': 'Wheat',
    'crop.rice': 'Rice',
    'crop.corn': 'Corn',
    'crop.cotton': 'Cotton',
    'crop.sugarcane': 'Sugarcane',
    'crop.season.rabi': 'Rabi',
    'crop.season.kharif': 'Kharif',
    'crop.season.year-round': 'Year-round',
    'task.fertilizer.application': 'Fertilizer Application',
    'task.fertilizer.application.desc': 'Apply first dose of nitrogen fertilizer',
    'task.irrigation.scheduling': 'Irrigation Scheduling',
    'task.irrigation.scheduling.desc': 'Schedule next irrigation based on soil moisture',
    'task.pest.monitoring': 'Pest Monitoring',
    'task.pest.monitoring.desc': 'Check for aphid infestation and other pests',
    'task.weed.management': 'Weed Management',
    'task.weed.management.desc': 'Remove weeds and apply herbicide if needed',
    'task.start': 'Start',
    'task.continue': 'Continue',
    'task.complete': 'Complete',
    
    // Financial Planning
    'financial.title': 'Financial Planning',
    'financial.subtitle': 'Budget planning, loans, and government schemes',
    'financial.calculator': 'Financial Calculator',
    'financial.farm.size': 'Farm Size (acres)',
    'financial.crop.type': 'Crop Type',
    'financial.season': 'Season',
    'financial.calculate': 'Calculate',
    'financial.total.investment': 'Total Investment',
    'financial.expected.revenue': 'Expected Revenue',
    'financial.net.profit': 'Net Profit',
    'financial.roi': 'ROI',
    'financial.per.acre': 'Per acre',
    'financial.return.on.investment': 'Return on Investment',
    'financial.loans': 'Loans',
    'financial.schemes': 'Schemes',
    'financial.planning': 'Planning',
    'financial.eligible': 'Eligible',
    'financial.not.eligible': 'Not Eligible',
    'financial.loan.amount': 'Loan Amount',
    'financial.interest.rate': 'Interest Rate',
    'financial.tenure': 'Tenure',
    'financial.emi': 'EMI',
    'financial.features': 'Features',
    'financial.apply.now': 'Apply Now',
    'financial.benefit': 'Benefit',
    'financial.eligibility': 'Eligibility',
    'financial.application.process': 'Application Process',
    'financial.deadline': 'Deadline',
    'financial.apply.scheme': 'Apply for Scheme',
    'financial.budget.planning': 'Budget Planning',
    'financial.seeds.fertilizers': 'Seeds & Fertilizers',
    'financial.labor.costs': 'Labor Costs',
    'financial.equipment': 'Equipment',
    'financial.irrigation': 'Irrigation',
    'financial.risk.management': 'Risk Management',
    'financial.weather.risk': 'Weather Risk',
    'financial.weather.risk.desc': 'Consider crop insurance for weather protection',
    'financial.insurance.coverage': 'Insurance Coverage',
    'financial.insurance.coverage.desc': 'PMFBY provides comprehensive crop insurance',
    'financial.download.report': 'Download Report',
    
    // Farmer Community
    'community.title': 'Farmer Community',
    'community.subtitle': 'Connect, share, and learn from fellow farmers',
    'community.posts': 'Posts',
    'community.groups': 'Groups',
    'community.experts': 'Experts',
    'community.create.post': 'Create Post',
    'community.post.title': 'Post title...',
    'community.post.content': 'Share your farming experience, ask questions, or provide tips...',
    'community.tags': 'Tags (comma separated)',
    'community.share.post': 'Share Post',
    'community.filter.all': 'All',
    'community.category.question': 'Question',
    'community.category.tip': 'Tip',
    'community.category.success': 'Success Story',
    'community.category.problem': 'Problem',
    'community.category.market': 'Market Update',
    'community.members': 'Members',
    'community.last.activity': 'Last Activity',
    'community.join.group': 'Join Group',
    'community.leave.group': 'Leave Group',
    'community.available': 'Available',
    'community.busy': 'Busy',
    'community.experience': 'Experience',
    'community.rating': 'Rating',
    'community.consultation.fee': 'Consultation Fee',
    'community.availability': 'Availability',
    'community.book.consultation': 'Book Consultation',
    'community.not.available': 'Not Available',
    
    // Offline Functionality
    'offline.connected': 'Connected to Internet',
    'offline.disconnected': 'Working Offline',
    'offline.online': 'Online',
    'offline.offline': 'Offline',
    'offline.working.offline': 'Your data will sync when connection is restored',
    'offline.syncing': 'Syncing',
    'offline.items': 'items',
    'offline.sync.failed': 'items failed to sync',
    
    // Government Schemes
    'government.title': 'Government Schemes',
    'government.subtitle': 'Access government benefits and schemes for farmers',
    'government.search.schemes': 'Search schemes...',
    'government.filter.all': 'All Categories',
    'government.category.financial': 'Financial',
    'government.category.insurance': 'Insurance',
    'government.category.technology': 'Technology',
    'government.category.training': 'Training',
    'government.category.infrastructure': 'Infrastructure',
    'government.schemes': 'Schemes',
    'government.applications': 'My Applications',
    'government.benefits': 'Benefits',
    'government.benefit': 'Benefit',
    'government.beneficiaries': 'Beneficiaries',
    'government.budget': 'Budget',
    'government.deadline': 'Deadline',
    'government.apply': 'Apply',
    'government.details': 'Details',
    'government.submitted': 'Submitted',
    'government.last.updated': 'Last Updated',
    'government.view.status': 'View Status',
    'government.total.benefits': 'Total Benefits',
    'government.benefits.received': 'Benefits received this year',
    'government.active.schemes': 'Active Schemes',
    'government.schemes.enrolled': 'Schemes enrolled in',
    'government.eligibility': 'Eligibility',
    'government.documents': 'Required Documents',
    'government.application.process': 'Application Process',
    'government.apply.now': 'Apply Now',
    'government.visit.website': 'Visit Website',
    'government.download.form': 'Download Form',
  },
  
  hi: {
    // Login Page
    'app.title': 'एग्रोएनालिटिक्स',
    'app.subtitle': 'स्मार्ट कृषि एनालिटिक्स प्लेटफॉर्म',
    'login.welcome': 'वापस स्वागत है',
    'login.description': 'एक बार का पासवर्ड प्राप्त करने के लिए अपना ईमेल दर्ज करें',
    'signup.title': 'खाता बनाएं',
    'signup.description': 'स्मार्ट एनालिटिक्स का उपयोग करने वाले हजारों किसानों से जुड़ें',
    'signup.verify': 'खाता निर्माण पूरा करने के लिए अपना ईमेल सत्यापित करें',
    'email.label': 'ईमेल पता',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'पूरा नाम',
    'name.placeholder': 'राम किसान',
    'farmSize.label': 'खेत का आकार (एकड़)',
    'farmSize.placeholder': '100',
    'otp.label': 'एक बार का पासवर्ड',
    'otp.placeholder': 'OTP दर्ज करें',
    'otp.expires': 'OTP समाप्त होता है:',
    'otp.resend': 'OTP पुनः भेजें',
    'send.otp': 'मेरे ईमेल पर OTP भेजें',
    'sending.otp': 'OTP भेजा जा रहा है...',
    'verifying': 'सत्यापित किया जा रहा है...',
    'get.started': 'शुरू करें',
    'send.verification': 'सत्यापन कोड भेजें',
    'complete.registration': 'पंजीकरण पूरा करें',
    'login.tab': 'लॉगिन',
    'signup.tab': 'साइन अप',
    'no.account': 'इस ईमेल के साथ कोई खाता नहीं मिला। कृपया पहले साइन अप करें।',
    'switch.tab': 'खाता नहीं है? एक बनाने के लिए "साइन अप" टैब पर स्विच करें।',
    'data.driven': 'डेटा-संचालित कृषि',
    'data.description': 'रियल-टाइम एनालिटिक्स, मौसम पूर्वानुमान और AI-संचालित फसल अंतर्दृष्टि के साथ सूचित निर्णय लें।',
    
    // Navbar
    'navbar.platform': 'स्मार्ट कृषि प्लेटफॉर्म',
    'navbar.notifications': 'सूचनाएं',
    'navbar.signout': 'साइन आउट',
    'navbar.profile': 'प्रोफाइल सेटिंग्स',
    'navbar.farm': 'खेत प्रबंधन',
    'navbar.subscription': 'सब्सक्रिप्शन',
    'navbar.logout': 'लॉगआउट',
    
    // Sidebar
    'sidebar.dashboard': 'डैशबोर्ड',
    'sidebar.weather': 'मौसम',
    'sidebar.soil': 'मिट्टी स्वास्थ्य',
    'sidebar.crop': 'फसल एनालिटिक्स',
    'sidebar.market': 'बाजार रुझान',
    'sidebar.reports': 'रिपोर्ट्स',
    
    // Dashboard
    'dashboard.title': 'खेत डैशबोर्ड',
    'dashboard.overview': 'खेत अवलोकन',
    'dashboard.weather': 'वर्तमान मौसम',
    'dashboard.temperature': 'तापमान',
    'dashboard.humidity': 'आर्द्रता',
    'dashboard.wind': 'हवा की गति',
    'dashboard.pressure': 'दबाव',
    'dashboard.visibility': 'दृश्यता',
    'dashboard.crop.analytics': 'फसल एनालिटिक्स',
    'dashboard.soil.health': 'मिट्टी स्वास्थ्य',
    'dashboard.market.trends': 'बाजार रुझान',
    'dashboard.recent.activity': 'हाल की गतिविधि',
    'dashboard.irrigation': 'सिंचाई स्थिति',
    'dashboard.fertilizer': 'उर्वरक अनुसूची',
    'dashboard.pest.control': 'कीट नियंत्रण',
    'dashboard.harvest': 'फसल योजना',
    
    // Language Selector
    'language.select': 'भाषा चुनें',
    'language.current': 'वर्तमान भाषा',
    
    // Voice Interface
    'voice.title': 'आवाज सहायक',
    'voice.listening': 'सुन रहा हूं...',
    'voice.speaking': 'बोल रहा हूं...',
    'voice.heard': 'आपने कहा',
    'voice.last.command': 'अंतिम आदेश',
    'voice.try.saying': 'कहने की कोशिश करें:',
    'voice.language.info': 'आवाज भाषा',
    'voice.not.supported': 'इस ब्राउज़र में आवाज सुविधाएं समर्थित नहीं हैं',
    'voice.commands.weather': 'आज का मौसम कैसा है?',
    'voice.commands.price': 'फसल की कीमतें क्या हैं?',
    'voice.commands.crop': 'मुझे फसल सलाह दें',
    'voice.commands.soil': 'मिट्टी की जांच करें',
    'voice.commands.help': 'मेरी मदद करें',
    'voice.weather.response': 'आज का मौसम धूप वाला है 28°C तापमान के साथ। खेती के लिए अच्छा है।',
    'voice.price.response': 'वर्तमान गेहूं की कीमत ₹2,950 प्रति क्विंटल, चावल ₹3,750 प्रति क्विंटल। कीमतें बढ़ रही हैं।',
    'voice.crop.response': 'इस मौसम के लिए, मैं गेहूं या चावल लगाने की सलाह देता हूं। उचित सिंचाई सुनिश्चित करें।',
    'voice.soil.response': 'आपकी मिट्टी का pH 6.8 है, जो अच्छा है। जैविक पदार्थ बढ़ाने के लिए कंपोस्ट डालें।',
    'voice.help.response': 'मैं आपकी मौसम अपडेट, फसल कीमतें, खेती सलाह और मिट्टी जानकारी में मदद कर सकता हूं।',
    'voice.unknown.response': 'मैं समझ नहीं पाया। मौसम, कीमतें, फसल या मिट्टी के बारे में पूछने की कोशिश करें।',
  },
  
  bn: {
    // Login Page
    'app.title': 'এগ্রোএনালিটিক্স',
    'app.subtitle': 'স্মার্ট কৃষি এনালিটিক্স প্ল্যাটফর্ম',
    'login.welcome': 'ফিরে স্বাগতম',
    'login.description': 'একবারের পাসওয়ার্ড পেতে আপনার ইমেইল লিখুন',
    'signup.title': 'অ্যাকাউন্ট তৈরি করুন',
    'signup.description': 'স্মার্ট এনালিটিক্স ব্যবহারকারী হাজারো কৃষকের সাথে যুক্ত হন',
    'signup.verify': 'অ্যাকাউন্ট তৈরি সম্পূর্ণ করতে আপনার ইমেইল যাচাই করুন',
    'email.label': 'ইমেইল ঠিকানা',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'পূর্ণ নাম',
    'name.placeholder': 'রাম কৃষক',
    'farmSize.label': 'খামারের আকার (একর)',
    'farmSize.placeholder': '100',
    'otp.label': 'একবারের পাসওয়ার্ড',
    'otp.placeholder': 'OTP লিখুন',
    'otp.expires': 'OTP মেয়াদ শেষ:',
    'otp.resend': 'OTP আবার পাঠান',
    'send.otp': 'আমার ইমেইলে OTP পাঠান',
    'sending.otp': 'OTP পাঠানো হচ্ছে...',
    'verifying': 'যাচাই করা হচ্ছে...',
    'get.started': 'শুরু করুন',
    'send.verification': 'যাচাই কোড পাঠান',
    'complete.registration': 'নিবন্ধন সম্পূর্ণ করুন',
    'login.tab': 'লগইন',
    'signup.tab': 'সাইন আপ',
    'no.account': 'এই ইমেইলে কোনো অ্যাকাউন্ট পাওয়া যায়নি। দয়া করে প্রথমে সাইন আপ করুন।',
    'switch.tab': 'অ্যাকাউন্ট নেই? একটি তৈরি করতে "সাইন আপ" ট্যাবে যান।',
    'data.driven': 'ডেটা-চালিত কৃষি',
    'data.description': 'রিয়েল-টাইম এনালিটিক্স, আবহাওয়ার পূর্বাভাস এবং AI-চালিত ফসলের অন্তর্দৃষ্টি দিয়ে সচেতন সিদ্ধান্ত নিন।',
    
    // Navbar
    'navbar.platform': 'স্মার্ট কৃষি প্ল্যাটফর্ম',
    'navbar.notifications': 'বিজ্ঞপ্তি',
    'navbar.signout': 'সাইন আউট',
    'navbar.profile': 'প্রোফাইল সেটিংস',
    'navbar.farm': 'খামার ব্যবস্থাপনা',
    'navbar.subscription': 'সাবস্ক্রিপশন',
    'navbar.logout': 'লগআউট',
    
    // Sidebar
    'sidebar.dashboard': 'ড্যাশবোর্ড',
    'sidebar.weather': 'আবহাওয়া',
    'sidebar.soil': 'মাটি স্বাস্থ্য',
    'sidebar.crop': 'ফসল এনালিটিক্স',
    'sidebar.market': 'বাজার প্রবণতা',
    'sidebar.reports': 'রিপোর্ট',
    
    // Dashboard
    'dashboard.title': 'খামার ড্যাশবোর্ড',
    'dashboard.overview': 'খামার ওভারভিউ',
    'dashboard.weather': 'বর্তমান আবহাওয়া',
    'dashboard.temperature': 'তাপমাত্রা',
    'dashboard.humidity': 'আর্দ্রতা',
    'dashboard.wind': 'বাতাসের গতি',
    'dashboard.pressure': 'চাপ',
    'dashboard.visibility': 'দৃশ্যমানতা',
    'dashboard.crop.analytics': 'ফসল এনালিটিক্স',
    'dashboard.soil.health': 'মাটি স্বাস্থ্য',
    'dashboard.market.trends': 'বাজার প্রবণতা',
    'dashboard.recent.activity': 'সাম্প্রতিক কার্যক্রম',
    'dashboard.irrigation': 'সেচ অবস্থা',
    'dashboard.fertilizer': 'সার সময়সূচী',
    'dashboard.pest.control': 'পোকা নিয়ন্ত্রণ',
    'dashboard.harvest': 'ফসল পরিকল্পনা',
    
    // Language Selector
    'language.select': 'ভাষা নির্বাচন করুন',
    'language.current': 'বর্তমান ভাষা',
  },
  
  te: {
    // Login Page
    'app.title': 'ఎగ్రోఎనాలిటిక్స్',
    'app.subtitle': 'స్మార్ట్ వ్యవసాయ విశ్లేషణ ప్లాట్ఫారమ్',
    'login.welcome': 'మళ్లీ స్వాగతం',
    'login.description': 'ఒకసారి పాస్‌వర్డ్ పొందడానికి మీ ఇమెయిల్‌ను నమోదు చేయండి',
    'signup.title': 'ఖాతా సృష్టించండి',
    'signup.description': 'స్మార్ట్ విశ్లేషణను ఉపయోగించే వేలాది రైతులతో చేరండి',
    'signup.verify': 'ఖాతా సృష్టికి మీ ఇమెయిల్‌ను ధృవీకరించండి',
    'email.label': 'ఇమెయిల్ చిరునామా',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'పూర్తి పేరు',
    'name.placeholder': 'రామ్ రైతు',
    'farmSize.label': 'వ్యవసాయ భూమి పరిమాణం (ఎకరాలు)',
    'farmSize.placeholder': '100',
    'otp.label': 'ఒకసారి పాస్‌వర్డ్',
    'otp.placeholder': 'OTP నమోదు చేయండి',
    'otp.expires': 'OTP గడువు ముగుస్తుంది:',
    'otp.resend': 'OTP మళ్లీ పంపండి',
    'send.otp': 'నా ఇమెయిల్‌కు OTP పంపండి',
    'sending.otp': 'OTP పంపుతోంది...',
    'verifying': 'ధృవీకరిస్తోంది...',
    'get.started': 'ప్రారంభించండి',
    'send.verification': 'ధృవీకరణ కోడ్ పంపండి',
    'complete.registration': 'నమోదు పూర్తి చేయండి',
    'login.tab': 'లాగిన్',
    'signup.tab': 'సైన్ అప్',
    'no.account': 'ఈ ఇమెయిల్‌తో ఖాతా కనుగొనబడలేదు. దయచేసి మొదట సైన్ అప్ చేయండి.',
    'switch.tab': 'ఖాతా లేదా? ఒకదాన్ని సృష్టించడానికి "సైన్ అప్" ట్యాబ్‌కు మారండి.',
    'data.driven': 'డేటా-ఆధారిత వ్యవసాయం',
    'data.description': 'రియల్-టైమ్ విశ్లేషణ, వాతావరణ అంచనాలు మరియు AI-ఆధారిత పంట అంతర్దృష్టులతో సమాచారపూర్వక నిర్ణయాలు తీసుకోండి.',
    
    // Navbar
    'navbar.platform': 'స్మార్ట్ వ్యవసాయ ప్లాట్ఫారమ్',
    'navbar.notifications': 'నోటిఫికేషన్‌లు',
    'navbar.signout': 'సైన్ అవుట్',
    'navbar.profile': 'ప్రొఫైల్ సెట్టింగ్‌లు',
    'navbar.farm': 'వ్యవసాయ నిర్వహణ',
    'navbar.subscription': 'సభ్యత్వం',
    'navbar.logout': 'లాగ్ అవుట్',
    
    // Sidebar
    'sidebar.dashboard': 'డ్యాష్‌బోర్డ్',
    'sidebar.weather': 'వాతావరణం',
    'sidebar.soil': 'నేల ఆరోగ్యం',
    'sidebar.crop': 'పంట విశ్లేషణ',
    'sidebar.market': 'మార్కెట్ ట్రెండ్‌లు',
    'sidebar.reports': 'రిపోర్ట్‌లు',
    
    // Dashboard
    'dashboard.title': 'వ్యవసాయ డ్యాష్‌బోర్డ్',
    'dashboard.overview': 'వ్యవసాయ అవలోకనం',
    'dashboard.weather': 'ప్రస్తుత వాతావరణం',
    'dashboard.temperature': 'ఉష్ణోగ్రత',
    'dashboard.humidity': 'ఆర్ద్రత',
    'dashboard.wind': 'గాలి వేగం',
    'dashboard.pressure': 'ఒత్తిడి',
    'dashboard.visibility': 'దృశ్యత',
    'dashboard.crop.analytics': 'పంట విశ్లేషణ',
    'dashboard.soil.health': 'నేల ఆరోగ్యం',
    'dashboard.market.trends': 'మార్కెట్ ట్రెండ్‌లు',
    'dashboard.recent.activity': 'ఇటీవలి కార్యకలాపం',
    'dashboard.irrigation': 'నీటిపారుదల స్థితి',
    'dashboard.fertilizer': 'ఎరువు షెడ్యూల్',
    'dashboard.pest.control': 'కీటక నియంత్రణ',
    'dashboard.harvest': 'పంట ప్రణాళిక',
    
    // Language Selector
    'language.select': 'భాషను ఎంచుకోండి',
    'language.current': 'ప్రస్తుత భాష',
  },
  
  mr: {
    // Login Page
    'app.title': 'एग्रोएनालिटिक्स',
    'app.subtitle': 'स्मार्ट कृषी विश्लेषण प्लॅटफॉर्म',
    'login.welcome': 'पुन्हा स्वागत',
    'login.description': 'एक-वेळचा पासवर्ड मिळवण्यासाठी आपला ईमेल प्रविष्ट करा',
    'signup.title': 'खाते तयार करा',
    'signup.description': 'स्मार्ट विश्लेषण वापरणाऱ्या हजारो शेतकऱ्यांसोबत सामील व्हा',
    'signup.verify': 'खाते निर्माण पूर्ण करण्यासाठी आपला ईमेल सत्यापित करा',
    'email.label': 'ईमेल पत्ता',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'पूर्ण नाव',
    'name.placeholder': 'राम शेतकरी',
    'farmSize.label': 'शेताचा आकार (एकर)',
    'farmSize.placeholder': '100',
    'otp.label': 'एक-वेळचा पासवर्ड',
    'otp.placeholder': 'OTP प्रविष्ट करा',
    'otp.expires': 'OTP कालबाह्य:',
    'otp.resend': 'OTP पुन्हा पाठवा',
    'send.otp': 'माझ्या ईमेलवर OTP पाठवा',
    'sending.otp': 'OTP पाठवत आहे...',
    'verifying': 'सत्यापित करत आहे...',
    'get.started': 'सुरू करा',
    'send.verification': 'सत्यापन कोड पाठवा',
    'complete.registration': 'नोंदणी पूर्ण करा',
    'login.tab': 'लॉगिन',
    'signup.tab': 'साइन अप',
    'no.account': 'या ईमेलसह कोणतेही खाते सापडले नाही. कृपया प्रथम साइन अप करा.',
    'switch.tab': 'खाते नाही? तयार करण्यासाठी "साइन अप" टॅबवर स्विच करा.',
    'data.driven': 'डेटा-चालित कृषी',
    'data.description': 'रिअल-टाइम विश्लेषण, हवामान अंदाज आणि AI-चालित पिक अंतर्दृष्टीसह माहितीपूर्ण निर्णय घ्या.',
    
    // Navbar
    'navbar.platform': 'स्मार्ट कृषी प्लॅटफॉर्म',
    'navbar.notifications': 'सूचना',
    'navbar.signout': 'साइन आउट',
    'navbar.profile': 'प्रोफाइल सेटिंग्ज',
    'navbar.farm': 'शेत व्यवस्थापन',
    'navbar.subscription': 'सदस्यता',
    'navbar.logout': 'लॉगआउट',
    
    // Sidebar
    'sidebar.dashboard': 'डॅशबोर्ड',
    'sidebar.weather': 'हवामान',
    'sidebar.soil': 'माती आरोग्य',
    'sidebar.crop': 'पिक विश्लेषण',
    'sidebar.market': 'बाजार प्रवृत्ती',
    'sidebar.reports': 'अहवाल',
    
    // Dashboard
    'dashboard.title': 'शेत डॅशबोर्ड',
    'dashboard.overview': 'शेत अवलोकन',
    'dashboard.weather': 'सध्याचे हवामान',
    'dashboard.temperature': 'तापमान',
    'dashboard.humidity': 'आर्द्रता',
    'dashboard.wind': 'वाऱ्याचा वेग',
    'dashboard.pressure': 'दाब',
    'dashboard.visibility': 'दृश्यता',
    'dashboard.crop.analytics': 'पिक विश्लेषण',
    'dashboard.soil.health': 'माती आरोग्य',
    'dashboard.market.trends': 'बाजार प्रवृत्ती',
    'dashboard.recent.activity': 'अलीकडील क्रियाकलाप',
    'dashboard.irrigation': 'सिंचन स्थिती',
    'dashboard.fertilizer': 'खत वेळापत्रक',
    'dashboard.pest.control': 'कीटक नियंत्रण',
    'dashboard.harvest': 'पिक योजना',
    
    // Language Selector
    'language.select': 'भाषा निवडा',
    'language.current': 'सध्याची भाषा',
  },
  
  ta: {
    // Login Page
    'app.title': 'எக்ரோஅனலிடிக்ஸ்',
    'app.subtitle': 'ஸ்மார்ட் விவசாய பகுப்பாய்வு தளம்',
    'login.welcome': 'மீண்டும் வரவேற்கிறோம்',
    'login.description': 'ஒரு முறை கடவுச்சொல் பெற உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    'signup.title': 'கணக்கு உருவாக்கவும்',
    'signup.description': 'ஸ்மார்ட் பகுப்பாய்வு பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் இணையுங்கள்',
    'signup.verify': 'கணக்கு உருவாக்கத்தை முடிக்க உங்கள் மின்னஞ்சலை சரிபார்க்கவும்',
    'email.label': 'மின்னஞ்சல் முகவரி',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'முழு பெயர்',
    'name.placeholder': 'ராம் விவசாயி',
    'farmSize.label': 'பண்ணை அளவு (ஏக்கர்)',
    'farmSize.placeholder': '100',
    'otp.label': 'ஒரு முறை கடவுச்சொல்',
    'otp.placeholder': 'OTP உள்ளிடவும்',
    'otp.expires': 'OTP காலாவதி:',
    'otp.resend': 'OTP மீண்டும் அனுப்பவும்',
    'send.otp': 'எனது மின்னஞ்சலுக்கு OTP அனுப்பவும்',
    'sending.otp': 'OTP அனுப்பப்படுகிறது...',
    'verifying': 'சரிபார்க்கப்படுகிறது...',
    'get.started': 'தொடங்கவும்',
    'send.verification': 'சரிபார்ப்பு குறியீடு அனுப்பவும்',
    'complete.registration': 'பதிவு முடிக்கவும்',
    'login.tab': 'உள்நுழைவு',
    'signup.tab': 'பதிவு செய்யவும்',
    'no.account': 'இந்த மின்னஞ்சலுடன் கணக்கு கிடைக்கவில்லை. முதலில் பதிவு செய்யவும்.',
    'switch.tab': 'கணக்கு இல்லையா? உருவாக்க "பதிவு செய்யவும்" தாவலுக்கு மாறவும்.',
    'data.driven': 'தரவு-ஆதார விவசாயம்',
    'data.description': 'நிகழ்நேர பகுப்பாய்வு, வானிலை கணிப்புகள் மற்றும் AI-ஆதார பயிர் நுண்ணறிவுகளுடன் தகவலறிந்த முடிவுகளை எடுக்கவும்.',
    
    // Navbar
    'navbar.platform': 'ஸ்மார்ட் விவசாய தளம்',
    'navbar.notifications': 'அறிவிப்புகள்',
    'navbar.signout': 'வெளியேறவும்',
    'navbar.profile': 'சுயவிவர அமைப்புகள்',
    'navbar.farm': 'பண்ணை மேலாண்மை',
    'navbar.subscription': 'சந்தா',
    'navbar.logout': 'வெளியேறவும்',
    
    // Sidebar
    'sidebar.dashboard': 'டாஷ்போர்டு',
    'sidebar.weather': 'வானிலை',
    'sidebar.soil': 'மண் ஆரோக்கியம்',
    'sidebar.crop': 'பயிர் பகுப்பாய்வு',
    'sidebar.market': 'சந்தை போக்குகள்',
    'sidebar.reports': 'அறிக்கைகள்',
    
    // Dashboard
    'dashboard.title': 'பண்ணை டாஷ்போர்டு',
    'dashboard.overview': 'பண்ணை கண்ணோட்டம்',
    'dashboard.weather': 'தற்போதைய வானிலை',
    'dashboard.temperature': 'வெப்பநிலை',
    'dashboard.humidity': 'ஈரப்பதம்',
    'dashboard.wind': 'காற்று வேகம்',
    'dashboard.pressure': 'அழுத்தம்',
    'dashboard.visibility': 'கண்ணுக்குத் தெரிவு',
    'dashboard.crop.analytics': 'பயிர் பகுப்பாய்வு',
    'dashboard.soil.health': 'மண் ஆரோக்கியம்',
    'dashboard.market.trends': 'சந்தை போக்குகள்',
    'dashboard.recent.activity': 'சமீபத்திய செயல்பாடு',
    'dashboard.irrigation': 'நீர்ப்பாசன நிலை',
    'dashboard.fertilizer': 'உர அட்டவணை',
    'dashboard.pest.control': 'பூச்சி கட்டுப்பாடு',
    'dashboard.harvest': 'அறுவடை திட்டம்',
    
    // Language Selector
    'language.select': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'language.current': 'தற்போதைய மொழி',
  },
  
  gu: {
    // Login Page
    'app.title': 'એગ્રોએનાલિટિક્સ',
    'app.subtitle': 'સ્માર્ટ એગ્રિકલ્ચર એનાલિટિક્સ પ્લેટફોર્મ',
    'login.welcome': 'પાછા સ્વાગત',
    'login.description': 'એક-વખતનો પાસવર્ડ મેળવવા માટે તમારો ઇમેઇલ દાખલ કરો',
    'signup.title': 'એકાઉન્ટ બનાવો',
    'signup.description': 'સ્માર્ટ એનાલિટિક્સ વાપરતા હજારો ખેડૂતો સાથે જોડાઓ',
    'signup.verify': 'એકાઉન્ટ બનાવવા માટે તમારો ઇમેઇલ ચકાસો',
    'email.label': 'ઇમેઇલ સરનામું',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'પૂર્ણ નામ',
    'name.placeholder': 'રામ ખેડૂત',
    'farmSize.label': 'ખેતરનું કદ (એકર)',
    'farmSize.placeholder': '100',
    'otp.label': 'એક-વખતનો પાસવર્ડ',
    'otp.placeholder': 'OTP દાખલ કરો',
    'otp.expires': 'OTP સમાપ્તિ:',
    'otp.resend': 'OTP ફરીથી મોકલો',
    'send.otp': 'મારા ઇમેઇલ પર OTP મોકલો',
    'sending.otp': 'OTP મોકલી રહ્યું છે...',
    'verifying': 'ચકાસી રહ્યું છે...',
    'get.started': 'શરૂ કરો',
    'send.verification': 'ચકાસણી કોડ મોકલો',
    'complete.registration': 'નોંધણી પૂર્ણ કરો',
    'login.tab': 'લોગિન',
    'signup.tab': 'સાઇન અપ',
    'no.account': 'આ ઇમેઇલ સાથે કોઈ એકાઉન્ટ મળ્યું નથી. કૃપા કરીને પહેલા સાઇન અપ કરો.',
    'switch.tab': 'એકાઉન્ટ નથી? બનાવવા માટે "સાઇન અપ" ટેબ પર સ્વિચ કરો.',
    'data.driven': 'ડેટા-ચાલિત ખેતી',
    'data.description': 'રિઅલ-ટાઇમ એનાલિટિક્સ, હવામાનની આગાહી અને AI-ચાલિત પાકની સૂઝો સાથે માહિતીપૂર્ણ નિર્ણયો લો.',
    
    // Navbar
    'navbar.platform': 'સ્માર્ટ એગ્રિકલ્ચર પ્લેટફોર્મ',
    'navbar.notifications': 'સૂચનાઓ',
    'navbar.signout': 'સાઇન આઉટ',
    'navbar.profile': 'પ્રોફાઇલ સેટિંગ્સ',
    'navbar.farm': 'ખેતર વ્યવસ્થાપન',
    'navbar.subscription': 'સબ્સ્ક્રિપ્શન',
    'navbar.logout': 'લોગઆઉટ',
    
    // Sidebar
    'sidebar.dashboard': 'ડેશબોર્ડ',
    'sidebar.weather': 'હવામાન',
    'sidebar.soil': 'માટી આરોગ્ય',
    'sidebar.crop': 'પાક એનાલિટિક્સ',
    'sidebar.market': 'બજારના વલણો',
    'sidebar.reports': 'રિપોર્ટ્સ',
    
    // Dashboard
    'dashboard.title': 'ખેતર ડેશબોર્ડ',
    'dashboard.overview': 'ખેતર અવલોકન',
    'dashboard.weather': 'વર્તમાન હવામાન',
    'dashboard.temperature': 'તાપમાન',
    'dashboard.humidity': 'આર્દ્રતા',
    'dashboard.wind': 'પવનની ગતિ',
    'dashboard.pressure': 'દબાણ',
    'dashboard.visibility': 'દૃશ્યતા',
    'dashboard.crop.analytics': 'પાક એનાલિટિક્સ',
    'dashboard.soil.health': 'માટી આરોગ્ય',
    'dashboard.market.trends': 'બજારના વલણો',
    'dashboard.recent.activity': 'તાજેતરની પ્રવૃત્તિ',
    'dashboard.irrigation': 'સિંચાઈ સ્થિતિ',
    'dashboard.fertilizer': 'ખાતર શેડ્યૂલ',
    'dashboard.pest.control': 'કીટક નિયંત્રણ',
    'dashboard.harvest': 'પાક યોજના',
    
    // Language Selector
    'language.select': 'ભાષા પસંદ કરો',
    'language.current': 'વર્તમાન ભાષા',
  },
  
  kn: {
    // Login Page
    'app.title': 'ಎಗ್ರೋಎನಾಲಿಟಿಕ್ಸ್',
    'app.subtitle': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ವಿಶ್ಲೇಷಣೆ ಪ್ಲಾಟ್ಫಾರ್ಮ್',
    'login.welcome': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'login.description': 'ಒಮ್ಮೆ ಪಾಸ್‌ವರ್ಡ್ ಪಡೆಯಲು ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    'signup.title': 'ಖಾತೆ ರಚಿಸಿ',
    'signup.description': 'ಸ್ಮಾರ್ಟ್ ವಿಶ್ಲೇಷಣೆ ಬಳಸುವ ಸಾವಿರಾರು ರೈತರೊಂದಿಗೆ ಸೇರಿ',
    'signup.verify': 'ಖಾತೆ ರಚಿಸಲು ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ',
    'email.label': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'ಪೂರ್ಣ ಹೆಸರು',
    'name.placeholder': 'ರಾಮ ರೈತ',
    'farmSize.label': 'ಫಾರ್ಮ್ ಗಾತ್ರ (ಎಕರೆ)',
    'farmSize.placeholder': '100',
    'otp.label': 'ಒಮ್ಮೆ ಪಾಸ್‌ವರ್ಡ್',
    'otp.placeholder': 'OTP ನಮೂದಿಸಿ',
    'otp.expires': 'OTP ಅವಧಿ ಮುಗಿಯುತ್ತದೆ:',
    'otp.resend': 'OTP ಮತ್ತೆ ಕಳುಹಿಸಿ',
    'send.otp': 'ನನ್ನ ಇಮೇಲ್‌ಗೆ OTP ಕಳುಹಿಸಿ',
    'sending.otp': 'OTP ಕಳುಹಿಸುತ್ತಿದೆ...',
    'verifying': 'ಪರಿಶೀಲಿಸುತ್ತಿದೆ...',
    'get.started': 'ಪ್ರಾರಂಭಿಸಿ',
    'send.verification': 'ಪರಿಶೀಲನೆ ಕೋಡ್ ಕಳುಹಿಸಿ',
    'complete.registration': 'ನೋಂದಣಿ ಪೂರ್ಣಗೊಳಿಸಿ',
    'login.tab': 'ಲಾಗಿನ್',
    'signup.tab': 'ಸೈನ್ ಅಪ್',
    'no.account': 'ಈ ಇಮೇಲ್‌ನೊಂದಿಗೆ ಯಾವುದೇ ಖಾತೆ ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೊದಲು ಸೈನ್ ಅಪ್ ಮಾಡಿ.',
    'switch.tab': 'ಖಾತೆ ಇಲ್ಲವೇ? ರಚಿಸಲು "ಸೈನ್ ಅಪ್" ಟ್ಯಾಬ್‌ಗೆ ಬದಲಾಯಿಸಿ.',
    'data.driven': 'ಡೇಟಾ-ಚಾಲಿತ ಕೃಷಿ',
    'data.description': 'ರಿಯಲ್-ಟೈಮ್ ವಿಶ್ಲೇಷಣೆ, ಹವಾಮಾನ predಿಕ್ಷನ್‌ಗಳು ಮತ್ತು AI-ಚಾಲಿತ ಬೆಳೆ ಒಳನೋಟಗಳೊಂದಿಗೆ ಮಾಹಿತಿಪೂರ್ಣ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.',
    
    // Navbar
    'navbar.platform': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಪ್ಲಾಟ್ಫಾರ್ಮ್',
    'navbar.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'navbar.signout': 'ಸೈನ್ ಅೌಟ್',
    'navbar.profile': 'ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'navbar.farm': 'ಫಾರ್ಮ್ ನಿರ್ವಹಣೆ',
    'navbar.subscription': 'ಚಂದಾ',
    'navbar.logout': 'ಲಾಗ್‌ಅೌಟ್',
    
    // Sidebar
    'sidebar.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'sidebar.weather': 'ಹವಾಮಾನ',
    'sidebar.soil': 'ಮಣ್ಣು ಆರೋಗ್ಯ',
    'sidebar.crop': 'ಬೆಳೆ ವಿಶ್ಲೇಷಣೆ',
    'sidebar.market': 'ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿಗಳು',
    'sidebar.reports': 'ವರದಿಗಳು',
    
    // Dashboard
    'dashboard.title': 'ಫಾರ್ಮ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'dashboard.overview': 'ಫಾರ್ಮ್ ಅವಲೋಕನ',
    'dashboard.weather': 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ',
    'dashboard.temperature': 'ತಾಪಮಾನ',
    'dashboard.humidity': 'ಆರ್ದ್ರತೆ',
    'dashboard.wind': 'ಗಾಳಿಯ ವೇಗ',
    'dashboard.pressure': 'ಒತ್ತಡ',
    'dashboard.visibility': 'ದೃಶ್ಯತೆ',
    'dashboard.crop.analytics': 'ಬೆಳೆ ವಿಶ್ಲೇಷಣೆ',
    'dashboard.soil.health': 'ಮಣ್ಣು ಆರೋಗ್ಯ',
    'dashboard.market.trends': 'ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿಗಳು',
    'dashboard.recent.activity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    'dashboard.irrigation': 'ನೀರಾವರಿ ಸ್ಥಿತಿ',
    'dashboard.fertilizer': 'ಗೊಬ್ಬರ ವೇಳಾಪಟ್ಟಿ',
    'dashboard.pest.control': 'ಕೀಟ ನಿಯಂತ್ರಣ',
    'dashboard.harvest': 'ಬೆಳೆ ಯೋಜನೆ',
    
    // Language Selector
    'language.select': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'language.current': 'ಪ್ರಸ್ತುತ ಭಾಷೆ',
  },
  
  ml: {
    // Login Page
    'app.title': 'എഗ്രോഎനാലിറ്റിക്സ്',
    'app.subtitle': 'സ്മാർട്ട് കാർഷിക വിശകലന പ്ലാറ്റ്ഫോം',
    'login.welcome': 'വീണ്ടും സ്വാഗതം',
    'login.description': 'ഒരിക്കൽ പാസ്‌വേഡ് ലഭിക്കാൻ നിങ്ങളുടെ ഇമെയിൽ നൽകുക',
    'signup.title': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'signup.description': 'സ്മാർട്ട് വിശകലനം ഉപയോഗിക്കുന്ന ആയിരക്കണക്കിന് കർഷകരുമായി ചേരുക',
    'signup.verify': 'അക്കൗണ്ട് സൃഷ്ടിക്കാൻ നിങ്ങളുടെ ഇമെയിൽ പരിശോധിക്കുക',
    'email.label': 'ഇമെയിൽ വിലാസം',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'പൂർണ്ണ നാമം',
    'name.placeholder': 'രാം കർഷകൻ',
    'farmSize.label': 'കൃഷിഭൂമി വലിപ്പം (ഏക്കർ)',
    'farmSize.placeholder': '100',
    'otp.label': 'ഒരിക്കൽ പാസ്‌വേഡ്',
    'otp.placeholder': 'OTP നൽകുക',
    'otp.expires': 'OTP കാലാവധി:',
    'otp.resend': 'OTP വീണ്ടും അയയ്ക്കുക',
    'send.otp': 'എന്റെ ഇമെയിലിലേക്ക് OTP അയയ്ക്കുക',
    'sending.otp': 'OTP അയയ്ക്കുന്നു...',
    'verifying': 'പരിശോധിക്കുന്നു...',
    'get.started': 'ആരംഭിക്കുക',
    'send.verification': 'പരിശോധന കോഡ് അയയ്ക്കുക',
    'complete.registration': 'രജിസ്ട്രേഷൻ പൂർത്തിയാക്കുക',
    'login.tab': 'ലോഗിൻ',
    'signup.tab': 'സൈൻ അപ്പ്',
    'no.account': 'ഈ ഇമെയിലുമായി യാതൊരു അക്കൗണ്ടും കണ്ടെത്തിയില്ല. ദയവായി ആദ്യം സൈൻ അപ്പ് ചെയ്യുക.',
    'switch.tab': 'അക്കൗണ്ട് ഇല്ലേ? സൃഷ്ടിക്കാൻ "സൈൻ അപ്പ്" ടാബിലേക്ക് മാറുക.',
    'data.driven': 'ഡാറ്റ-ചാലിത കാർഷികം',
    'data.description': 'റിയൽ-ടൈം വിശകലനം, കാലാവസ്ഥാ പ്രവചനങ്ങൾ, AI-ചാലിത വിള അന്തർദൃഷ്ടികൾ എന്നിവയുമായി വിവരപരമായ തീരുമാനങ്ങൾ എടുക്കുക.',
    
    // Navbar
    'navbar.platform': 'സ്മാർട്ട് കാർഷിക പ്ലാറ്റ്ഫോം',
    'navbar.notifications': 'അറിയിപ്പുകൾ',
    'navbar.signout': 'സൈൻ അൗട്ട്',
    'navbar.profile': 'പ്രൊഫൈൽ സെറ്റിംഗുകൾ',
    'navbar.farm': 'കൃഷിഭൂമി മാനേജ്മെന്റ്',
    'navbar.subscription': 'സബ്സ്ക്രിപ്ഷൻ',
    'navbar.logout': 'ലോഗ്‌അൗട്ട്',
    
    // Sidebar
    'sidebar.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'sidebar.weather': 'കാലാവസ്ഥ',
    'sidebar.soil': 'മണ്ണ് ആരോഗ്യം',
    'sidebar.crop': 'വിള വിശകലനം',
    'sidebar.market': 'മാർക്കറ്റ് പ്രവണതകൾ',
    'sidebar.reports': 'റിപ്പോർട്ടുകൾ',
    
    // Dashboard
    'dashboard.title': 'കൃഷിഭൂമി ഡാഷ്‌ബോർഡ്',
    'dashboard.overview': 'കൃഷിഭൂമി അവലോകനം',
    'dashboard.weather': 'നിലവിലെ കാലാവസ്ഥ',
    'dashboard.temperature': 'താപനില',
    'dashboard.humidity': 'ആർദ്രത',
    'dashboard.wind': 'കാറ്റിന്റെ വേഗത',
    'dashboard.pressure': 'മർദ്ദം',
    'dashboard.visibility': 'ദൃശ്യത',
    'dashboard.crop.analytics': 'വിള വിശകലനം',
    'dashboard.soil.health': 'മണ്ണ് ആരോഗ്യം',
    'dashboard.market.trends': 'മാർക്കറ്റ് പ്രവണതകൾ',
    'dashboard.recent.activity': 'സമീപകാല പ്രവർത്തനം',
    'dashboard.irrigation': 'ജലസേചന സ്ഥിതി',
    'dashboard.fertilizer': 'വള ഷെഡ്യൂൾ',
    'dashboard.pest.control': 'കീടനിയന്ത്രണം',
    'dashboard.harvest': 'വിള ആസൂത്രണം',
    
    // Language Selector
    'language.select': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    'language.current': 'നിലവിലെ ഭാഷ',
  },
  
  pa: {
    // Login Page
    'app.title': 'ਏਗਰੋਐਨਾਲਿਟਿਕਸ',
    'app.subtitle': 'ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਵਿਸ਼ਲੇਸ਼ਣ ਪਲੇਟਫਾਰਮ',
    'login.welcome': 'ਵਾਪਸ ਸਵਾਗਤ',
    'login.description': 'ਇੱਕ ਵਾਰ ਦਾ ਪਾਸਵਰਡ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਪਣਾ ਈਮੇਲ ਦਰਜ ਕਰੋ',
    'signup.title': 'ਖਾਤਾ ਬਣਾਓ',
    'signup.description': 'ਸਮਾਰਟ ਵਿਸ਼ਲੇਸ਼ਣ ਵਰਤ ਰਹੇ ਹਜ਼ਾਰਾਂ ਕਿਸਾਨਾਂ ਨਾਲ ਜੁੜੋ',
    'signup.verify': 'ਖਾਤਾ ਬਣਾਉਣ ਲਈ ਆਪਣਾ ਈਮੇਲ ਤਸਦੀਕ ਕਰੋ',
    'email.label': 'ਈਮੇਲ ਪਤਾ',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'ਪੂਰਾ ਨਾਮ',
    'name.placeholder': 'ਰਾਮ ਕਿਸਾਨ',
    'farmSize.label': 'ਖੇਤ ਦਾ ਆਕਾਰ (ਏਕੜ)',
    'farmSize.placeholder': '100',
    'otp.label': 'ਇੱਕ ਵਾਰ ਦਾ ਪਾਸਵਰਡ',
    'otp.placeholder': 'OTP ਦਰਜ ਕਰੋ',
    'otp.expires': 'OTP ਮਿਆਦ ਸਮਾਪਤ:',
    'otp.resend': 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
    'send.otp': 'ਮੇਰੇ ਈਮੇਲ \'ਤੇ OTP ਭੇਜੋ',
    'sending.otp': 'OTP ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    'verifying': 'ਤਸਦੀਕ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    'get.started': 'ਸ਼ੁਰੂ ਕਰੋ',
    'send.verification': 'ਤਸਦੀਕੀ ਕੋਡ ਭੇਜੋ',
    'complete.registration': 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਪੂਰਾ ਕਰੋ',
    'login.tab': 'ਲੌਗਇਨ',
    'signup.tab': 'ਸਾਈਨ ਅੱਪ',
    'no.account': 'ਇਸ ਈਮੇਲ ਨਾਲ ਕੋਈ ਖਾਤਾ ਨਹੀਂ ਮਿਲਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਸਾਈਨ ਅੱਪ ਕਰੋ।',
    'switch.tab': 'ਖਾਤਾ ਨਹੀਂ ਹੈ? ਬਣਾਉਣ ਲਈ "ਸਾਈਨ ਅੱਪ" ਟੈਬ \'ਤੇ ਜਾਓ।',
    'data.driven': 'ਡੇਟਾ-ਚਾਲਿਤ ਖੇਤੀਬਾੜੀ',
    'data.description': 'ਰੀਅਲ-ਟਾਈਮ ਵਿਸ਼ਲੇਸ਼ਣ, ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ ਅਤੇ AI-ਚਾਲਿਤ ਫਸਲ ਦੀ ਸੂਝ ਨਾਲ ਸੂਚਿਤ ਫੈਸਲੇ ਲਓ।',
    
    // Navbar
    'navbar.platform': 'ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਪਲੇਟਫਾਰਮ',
    'navbar.notifications': 'ਸੂਚਨਾਵਾਂ',
    'navbar.signout': 'ਸਾਈਨ ਆਉਟ',
    'navbar.profile': 'ਪ੍ਰੋਫਾਈਲ ਸੈਟਿੰਗਾਂ',
    'navbar.farm': 'ਖੇਤ ਪ੍ਰਬੰਧਨ',
    'navbar.subscription': 'ਗਾਹਕੀ',
    'navbar.logout': 'ਲੌਗਆਉਟ',
    
    // Sidebar
    'sidebar.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'sidebar.weather': 'ਮੌਸਮ',
    'sidebar.soil': 'ਮਿੱਟੀ ਸਿਹਤ',
    'sidebar.crop': 'ਫਸਲ ਵਿਸ਼ਲੇਸ਼ਣ',
    'sidebar.market': 'ਮਾਰਕੀਟ ਰੁਝਾਨ',
    'sidebar.reports': 'ਰਿਪੋਰਟਾਂ',
    
    // Dashboard
    'dashboard.title': 'ਖੇਤ ਡੈਸ਼ਬੋਰਡ',
    'dashboard.overview': 'ਖੇਤ ਦਾ ਜਾਇਜ਼ਾ',
    'dashboard.weather': 'ਮੌਜੂਦਾ ਮੌਸਮ',
    'dashboard.temperature': 'ਤਾਪਮਾਨ',
    'dashboard.humidity': 'ਨਮੀ',
    'dashboard.wind': 'ਹਵਾ ਦੀ ਗਤੀ',
    'dashboard.pressure': 'ਦਬਾਅ',
    'dashboard.visibility': 'ਦ੍ਰਿਸ਼ਟੀ',
    'dashboard.crop.analytics': 'ਫਸਲ ਵਿਸ਼ਲੇਸ਼ਣ',
    'dashboard.soil.health': 'ਮਿੱਟੀ ਸਿਹਤ',
    'dashboard.market.trends': 'ਮਾਰਕੀਟ ਰੁਝਾਨ',
    'dashboard.recent.activity': 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
    'dashboard.irrigation': 'ਸਿੰਚਾਈ ਸਥਿਤੀ',
    'dashboard.fertilizer': 'ਖਾਦ ਸਮਾਂ',
    'dashboard.pest.control': 'ਕੀਟ ਨਿਯੰਤਰਣ',
    'dashboard.harvest': 'ਫਸਲ ਯੋਜਨਾ',
    
    // Language Selector
    'language.select': 'ਭਾਸ਼ਾ ਚੁਣੋ',
    'language.current': 'ਮੌਜੂਦਾ ਭਾਸ਼ਾ',
  },
  
  or: {
    // Login Page
    'app.title': 'ଏଗ୍ରୋଏନାଲିଟିକ୍ସ',
    'app.subtitle': 'ସ୍ମାର୍ଟ କୃଷି ବିଶ୍ଳେଷଣ ପ୍ଲାଟଫର୍ମ',
    'login.welcome': 'ପୁନର୍ବାର ସ୍ୱାଗତ',
    'login.description': 'ଏକ-ଥର ପାସୱାର୍ଡ ପାଇବା ପାଇଁ ଆପଣଙ୍କର ଇମେଲ୍ ପ୍ରବେଶ କରନ୍ତୁ',
    'signup.title': 'ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ',
    'signup.description': 'ସ୍ମାର୍ଟ ବିଶ୍ଳେଷଣ ବ୍ୟବହାର କରୁଥିବା ହଜାର ହଜାର କୃଷକଙ୍କ ସହିତ ଯୋଗ ଦିଅନ୍ତୁ',
    'signup.verify': 'ଖାତା ସୃଷ୍ଟି ସମ୍ପୂର୍ଣ୍ଣ କରିବା ପାଇଁ ଆପଣଙ୍କର ଇମେଲ୍ ଯାଞ୍ଚ କରନ୍ତୁ',
    'email.label': 'ଇମେଲ୍ ଠିକଣା',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'ପୂର୍ଣ୍ଣ ନାମ',
    'name.placeholder': 'ରାମ କୃଷକ',
    'farmSize.label': 'ଖେତର ଆକାର (ଏକର)',
    'farmSize.placeholder': '100',
    'otp.label': 'ଏକ-ଥର ପାସୱାର୍ଡ',
    'otp.placeholder': 'OTP ପ୍ରବେଶ କରନ୍ତୁ',
    'otp.expires': 'OTP ସମୟ ସମାପ୍ତ:',
    'otp.resend': 'OTP ପୁନର୍ବାର ପଠାନ୍ତୁ',
    'send.otp': 'ମୋର ଇମେଲ୍‌କୁ OTP ପଠାନ୍ତୁ',
    'sending.otp': 'OTP ପଠାଉଛି...',
    'verifying': 'ଯାଞ୍ଚ କରୁଛି...',
    'get.started': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'send.verification': 'ଯାଞ୍ଚ କୋଡ୍ ପଠାନ୍ତୁ',
    'complete.registration': 'ନିବେଦନ ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
    'login.tab': 'ଲଗଇନ୍',
    'signup.tab': 'ସାଇନ୍ ଅପ୍',
    'no.account': 'ଏହି ଇମେଲ୍ ସହିତ କୌଣସି ଖାତା ମିଳିଲା ନାହିଁ। ଦୟାକରି ପ୍ରଥମେ ସାଇନ୍ ଅପ୍ କରନ୍ତୁ।',
    'switch.tab': 'ଖାତା ନାହିଁ? ସୃଷ୍ଟି କରିବା ପାଇଁ "ସାଇନ୍ ଅପ୍" ଟ୍ୟାବ୍‌କୁ ଯାଆନ୍ତୁ।',
    'data.driven': 'ଡାଟା-ଚାଳିତ କୃଷି',
    'data.description': 'ରିଅଲ୍-ଟାଇମ୍ ବିଶ୍ଳେଷଣ, ପାଣିପାଗ ପ୍ରବଚନ ଏବଂ AI-ଚାଳିତ ଫସଲ ଅନ୍ତର୍ଦୃଷ୍ଟି ସହିତ ସୂଚିତ ନିର୍ଣ୍ଣୟ ନିଅନ୍ତୁ।',
    
    // Navbar
    'navbar.platform': 'ସ୍ମାର୍ଟ କୃଷି ପ୍ଲାଟଫର୍ମ',
    'navbar.notifications': 'ବିଜ୍ଞପ୍ତି',
    'navbar.signout': 'ସାଇନ୍ ଆଉଟ୍',
    'navbar.profile': 'ପ୍ରୋଫାଇଲ୍ ସେଟିଂସ୍',
    'navbar.farm': 'ଖେତ ପରିଚାଳନା',
    'navbar.subscription': 'ସବସ୍କ୍ରିପ୍ସନ୍',
    'navbar.logout': 'ଲଗ୍‌ଆଉଟ୍',
    
    // Sidebar
    'sidebar.dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'sidebar.weather': 'ପାଣିପାଗ',
    'sidebar.soil': 'ମାଟି ସ୍ୱାସ୍ଥ୍ୟ',
    'sidebar.crop': 'ଫସଲ ବିଶ୍ଳେଷଣ',
    'sidebar.market': 'ବଜାର ପ୍ରବଣତା',
    'sidebar.reports': 'ରିପୋର୍ଟ',
    
    // Dashboard
    'dashboard.title': 'ଖେତ ଡ୍ୟାସବୋର୍ଡ',
    'dashboard.overview': 'ଖେତ ଅବଲୋକନ',
    'dashboard.weather': 'ବର୍ତ୍ତମାନ ପାଣିପାଗ',
    'dashboard.temperature': 'ତାପମାତ୍ରା',
    'dashboard.humidity': 'ଆର୍ଦ୍ରତା',
    'dashboard.wind': 'ବାୟୁ ବେଗ',
    'dashboard.pressure': 'ଚାପ',
    'dashboard.visibility': 'ଦୃଶ୍ୟତା',
    'dashboard.crop.analytics': 'ଫସଲ ବିଶ୍ଳେଷଣ',
    'dashboard.soil.health': 'ମାଟି ସ୍ୱାସ୍ଥ୍ୟ',
    'dashboard.market.trends': 'ବଜାର ପ୍ରବଣତା',
    'dashboard.recent.activity': 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
    'dashboard.irrigation': 'ସେଚନ ସ୍ଥିତି',
    'dashboard.fertilizer': 'ସାର କାର୍ଯ୍ୟକ୍ରମ',
    'dashboard.pest.control': 'କୀଟ ନିୟନ୍ତ୍ରଣ',
    'dashboard.harvest': 'ଫସଲ ଯୋଜନା',
    
    // Language Selector
    'language.select': 'ଭାଷା ବାଛନ୍ତୁ',
    'language.current': 'ବର୍ତ୍ତମାନ ଭାଷା',
  },
  
  as: {
    // Login Page
    'app.title': 'এগ্ৰোএনালিটিক্স',
    'app.subtitle': 'স্মাৰ্ট কৃষি বিশ্লেষণ প্লেটফৰ্ম',
    'login.welcome': 'পুনৰ স্বাগতম',
    'login.description': 'এক-বাৰৰ পাছৱৰ্ড পাবলৈ আপোনাৰ ইমেইল প্ৰৱেশ কৰক',
    'signup.title': 'একাউণ্ট সৃষ্টি কৰক',
    'signup.description': 'স্মাৰ্ট বিশ্লেষণ ব্যৱহাৰ কৰা হাজাৰ হাজাৰ খেতিয়কৰ সৈতে যুক্ত হওক',
    'signup.verify': 'একাউণ্ট সৃষ্টি সম্পূৰ্ণ কৰিবলৈ আপোনাৰ ইমেইল যাচাই কৰক',
    'email.label': 'ইমেইল ঠিকনা',
    'email.placeholder': 'kisan@example.com',
    'name.label': 'পূৰ্ণ নাম',
    'name.placeholder': 'ৰাম খেতিয়ক',
    'farmSize.label': 'খেতিৰ মাটিৰ পৰিমাণ (একৰ)',
    'farmSize.placeholder': '100',
    'otp.label': 'এক-বাৰৰ পাছৱৰ্ড',
    'otp.placeholder': 'OTP প্ৰৱেশ কৰক',
    'otp.expires': 'OTP সময় শেষ:',
    'otp.resend': 'OTP পুনৰ পঠিয়াওক',
    'send.otp': 'মোৰ ইমেইললৈ OTP পঠিয়াওক',
    'sending.otp': 'OTP পঠিয়াই আছে...',
    'verifying': 'যাচাই কৰি আছে...',
    'get.started': 'আৰম্ভ কৰক',
    'send.verification': 'যাচাই কোড পঠিয়াওক',
    'complete.registration': 'নিবন্ধন সম্পূৰ্ণ কৰক',
    'login.tab': 'লগইন',
    'signup.tab': 'ছাইন আপ',
    'no.account': 'এই ইমেইলৰ সৈতে কোনো একাউণ্ট পোৱা নগ\'ল। অনুগ্ৰহ কৰি প্ৰথমে ছাইন আপ কৰক।',
    'switch.tab': 'একাউণ্ট নাই? সৃষ্টি কৰিবলৈ "ছাইন আপ" টেবলৈ যাওক।',
    'data.driven': 'ডাটা-চালিত কৃষি',
    'data.description': 'ৰিয়েল-টাইম বিশ্লেষণ, বতৰৰ ভৱিষ্যদ্বাণী আৰু AI-চালিত শস্যৰ অন্তৰ্দৃষ্টিৰ সৈতে তথ্যপূৰ্ণ সিদ্ধান্ত লওক।',
    
    // Navbar
    'navbar.platform': 'স্মাৰ্ট কৃষি প্লেটফৰ্ম',
    'navbar.notifications': 'বিজ্ঞপ্তি',
    'navbar.signout': 'ছাইন আউট',
    'navbar.profile': 'প্ৰফাইল ছেটিংছ',
    'navbar.farm': 'খেতি পৰিচালনা',
    'navbar.subscription': 'চাবস্ক্ৰিপচন',
    'navbar.logout': 'লগআউট',
    
    // Sidebar
    'sidebar.dashboard': 'ড্যাশবৰ্ড',
    'sidebar.weather': 'বতৰ',
    'sidebar.soil': 'মাটিৰ স্বাস্থ্য',
    'sidebar.crop': 'শস্য বিশ্লেষণ',
    'sidebar.market': 'বজাৰৰ প্ৰবণতা',
    'sidebar.reports': 'ৰিপৰ্ট',
    
    // Dashboard
    'dashboard.title': 'খেতিৰ ড্যাশবৰ্ড',
    'dashboard.overview': 'খেতিৰ পৰিদৰ্শন',
    'dashboard.weather': 'বৰ্তমান বতৰ',
    'dashboard.temperature': 'তাপমাত্ৰা',
    'dashboard.humidity': 'আৰ্দ্ৰতা',
    'dashboard.wind': 'বতাহৰ গতি',
    'dashboard.pressure': 'চাপ',
    'dashboard.visibility': 'দৃশ্যমানতা',
    'dashboard.crop.analytics': 'শস্য বিশ্লেষণ',
    'dashboard.soil.health': 'মাটিৰ স্বাস্থ্য',
    'dashboard.market.trends': 'বজাৰৰ প্ৰবণতা',
    'dashboard.recent.activity': 'সাম্প্ৰতিক কাৰ্যকলাপ',
    'dashboard.irrigation': 'সেচনৰ অৱস্থা',
    'dashboard.fertilizer': 'সাৰৰ সময়সূচী',
    'dashboard.pest.control': 'কীট নিয়ন্ত্ৰণ',
    'dashboard.harvest': 'শস্য পৰিকল্পনা',
    
    // Language Selector
    'language.select': 'ভাষা বাছক',
    'language.current': 'বৰ্তমান ভাষা',
  }
};

// Language Context
interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
  languages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Language Provider
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<string>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage');
    if (savedLanguage && languages.find(lang => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when changed
  const setLanguage = (language: string) => {
    setCurrentLanguage(language);
    localStorage.setItem('selectedLanguage', language);
  };

  // Translation function
  const t = (key: string): string => {
    const translation = translations[currentLanguage as keyof typeof translations];
    return translation?.[key as keyof typeof translation] || translations.en[key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Hook to use language context
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
